AllCops:
  NewCops: enable
  Exclude:
  - 'Gemfile'
  - 'Gemfile.lock'

Style/Documentation:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Layout/LineLength:
  Exclude:
  - 'spec/**/*_spec.rb'

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*_spec.rb'