Style/Documentation:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
  - 'Gemfile'
  - 'Gemfile.lock'

Layout/LineLength:
  Exclude:
  - 'spec/**/*_spec.rb'

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*_spec.rb'